[package]
name = "signalr_rs"
version = "0.1.3"
authors = ["Guillaume Balaine <igosuki@gmail.com>"]
edition = "2018"
description = "SignalR client based on actix web client and async await"
keywords = [ "signalr", "actix" ]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/Igosuki/signalr-rs"
repository = "https://github.com/Igosuki/signalr-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[example]]
name = "bittrex_signalr"
path = "examples/bittrex.rs.rs"

[dependencies]
awc = "2.0.0-alpha.2"
actix-web = { version = "3.0.0-alpha.3", features = ["openssl"] }
actix = "0.10.0-alpha.3"
actix-http = "2.0.0-alpha.4"

serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
failure = "0.1"
url = "2.1"
actix-codec = "0.2"
futures = "0.3"
openssl = "0.10"
bytes = "0.5"
derive_more = "0.99"
base64 = "0.11"
libflate = "0.1"
log = "0.4"
env_logger = "0.7"
regex = "1.3"
lazy_static = "1.4"
backoff = "0.1"

[dev-dependencies]
actix-rt = "1.1"
tokio = "0.2"
